// Generated by BUCKLESCRIPT VERSION 5.0.4-dev.1, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as TimesSvg from "./times.svg";
import * as Button$ReactHooksTemplate from "./Button.bs.js";

((require('./App.css')));

function countWordsInString(text) {
  var spacesRegex = new RegExp("\\s+");
  if (text === "") {
    return 0;
  } else {
    return text.trim().split(spacesRegex).length;
  }
}

var make = TimesSvg.default;

var Times = /* module */[/* make */make];

function App(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setText = match[1];
  var text = match[0];
  var handleTextChange = function (e) {
    return Curry._1(setText, e.target.value);
  };
  var handleClearClick = function (param) {
    return Curry._1(setText, (function (param) {
                  return "";
                }));
  };
  var wordsCountText = String(countWordsInString(text)) + " words";
  return React.createElement("div", {
              className: "App"
            }, React.createElement("div", {
                  className: "Header"
                }, React.createElement("h3", undefined, "Word Counter"), React.createElement("span", undefined, wordsCountText)), React.createElement("textarea", {
                  placeholder: "Express yourself",
                  value: text,
                  onChange: handleTextChange
                }), React.createElement("div", {
                  className: "footer"
                }, React.createElement(Button$ReactHooksTemplate.make, {
                      onClick: handleClearClick,
                      title: "Clear text",
                      children: React.createElement(make, {
                            height: "20px"
                          }),
                      disabled: text.length === 0
                    })));
}

var make$1 = App;

export {
  countWordsInString ,
  Times ,
  make$1 as make,
  
}
/*  Not a pure module */
