// Generated by BUCKLESCRIPT VERSION 5.0.4-dev.1, PLEASE EDIT WITH CARE

import * as React from "react";

((require('./Button.css')));

function classNameOfCategory(category) {
  return "Button " + (
          category ? "primary" : "secondary"
        );
}

function Button(Props) {
  var onClick = Props.onClick;
  var title = Props.title;
  var children = Props.children;
  var match = Props.disabled;
  var disabled = match !== undefined ? match : false;
  var match$1 = Props.category;
  var category = match$1 !== undefined ? match$1 : /* SECONDARY */0;
  return React.createElement("button", {
              className: classNameOfCategory(category),
              title: title,
              disabled: disabled,
              onClick: onClick
            }, children);
}

var make = Button;

export {
  classNameOfCategory ,
  make ,
  
}
/*  Not a pure module */
