// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

((require('./Button.css')));

function classNameOfCategory(category) {
  return "Button " + (
          category ? "primary" : "secondary"
        );
}

function Button(Props) {
  var onClickOpt = Props.onClick;
  var title = Props.title;
  var children = Props.children;
  var disabledOpt = Props.disabled;
  var categoryOpt = Props.category;
  var onClick = onClickOpt !== undefined ? onClickOpt : (function (param) {
        
      });
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  var category = categoryOpt !== undefined ? categoryOpt : /* SECONDARY */0;
  return React.createElement("button", {
              className: classNameOfCategory(category),
              title: title,
              disabled: disabled,
              onClick: onClick
            }, children);
}

var make = Button;

export {
  classNameOfCategory ,
  make ,
  
}
/*  Not a pure module */
